kind: Secret
apiVersion: v1
metadata:
  name: keycloak-postgres
  namespace: default
  labels:
    app: keycloak
data:
  password: a2V5Y2xvYWs=
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: keycloak-theme
  namespace: default
  labels:
    app: keycloak
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak
  labels:
    app: keycloak
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - secretName: tls-iam-k8s-strix-kr
    hosts:
    - iam.k8s.strix.kr
  rules:
  - host: iam.k8s.strix.kr
    http:
      paths:
      - backend:
          serviceName: keycloak-http
          servicePort: 80
        path: /
---