kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: keycloak-themes
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
---