apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - secretName: deploy-k8s-strix-kr
    hosts:
    - deploy.k8s.strix.kr
  rules:
  - host: deploy.k8s.strix.kr
    http:
      paths:
      - backend:
          serviceName: jenkins
          servicePort: 8080
        path: /
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-agent
  namespace: dev
imagePullSecrets:
  - name: local-docker-registry-secret
---
# "jenkins-agent" has "admin" role for namespace dev
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-agent-bind-admin
  namespace: dev
subjects:
- kind: ServiceAccount
  name: jenkins-agent
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io