apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
      errors
      log
      health
      kubernetes cluster.local. in-addr.arpa ip6.arpa {
        pods insecure
        fallthrough in-addr.arpa ip6.arpa
        
        # google local dns server
        upstream 8.8.8.8 8.8.4.4
      }
      prometheus :9153
      proxy . /etc/resolv.conf
      cache 30
      reload
    }
---