apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: keycloak-postgres
  namespace: default
spec:
  version: "9.6"
  replicas: 1
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
---


