# apiVersion: v1
# kind: Secret
# metadata:
#   name: cert-manager-aws-route53
#   namespace: cert-manager
# type: Opaque
# data:
#   secret-access-key: b0pJSVN1RGVMOGFRTENkaXdjeUg3THJvS2doczdyNmE1S0c5RUM5dg==
# ---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: info@strix.co.kr

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-acme-credential

    # ACME DNS-01 provider configurations
    dns01:
      providers:
      - name: route53
        route53:
          region: ap-northeast-2
          # accessKeyId: AKIAIZYARUPSKE2DW3NQ
          # secretAccessKeySecretRef:
          #   name: cert-manager-aws-route53
          #   key: secret-access-key
---
