apiVersion: v1
kind: Secret
metadata:
  name: cert-manager
  namespace: default
type: Opaque
data:
  aws-route53-secret-access-key: Vm5LQXJwOC9oWXV3eENVVlBxbFg1MmJweWQ3SDJjRGdnVnZpTmJnTQo=
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: info@strix.co.kr

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-acme-credential

    # ACME DNS-01 provider configurations
    dns01:
      providers:
      - name: route53
        route53:
          region: ap-northeast-2
          accessKeyId: AKIAJXFYWBKLCPA3DJIQ
          secretAccessKeySecretRef:
            name: cert-manager
            key: aws-route53-secret-access-key
---
