apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: rbac-cluster-admin-sa-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: cluster-admin-sa
  namespace: kube-system
---

# To get the token
# kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep cluster-admin-sa | awk '{ print $1 }')

# To init helm
# helm init --service-account cluster-admin-sa --upgrade